package com.miniCRM.miniCRM.security;

// Ações do sistema (SPEC-01 §5). Os controllers pedem a ação, nunca o cargo.
public enum Permissao {
    CLIENTE_VER, CLIENTE_CRIAR, CLIENTE_EDITAR, CLIENTE_EXCLUIR, CLIENTE_TRANSFERIR,
    INTERACAO_VER, INTERACAO_CRIAR,
    OPORTUNIDADE_VER, OPORTUNIDADE_CRIAR, OPORTUNIDADE_EDITAR, OPORTUNIDADE_MOVER, OPORTUNIDADE_REABRIR,
    TAREFA_VER, TAREFA_CRIAR, TAREFA_EDITAR, TAREFA_CONCLUIR,
    NOTIFICACAO_VER, DASHBOARD_VER, RANKING_VER, RELATORIO_EXPORTAR,
    USUARIO_VER, USUARIO_CRIAR, USUARIO_EDITAR, USUARIO_DESATIVAR, USUARIO_ALTERAR_PERFIL
}
